// Generates src/constants/services.ts and src/utils/brand.ts from
// brands.data.mjs + the actual files in assets/brands/. Run after downloading
// logos: node scripts/generate-brands.mjs
import { writeFile, readdir } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { BRANDS } from './brands.data.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')

const initialOf = (name) => (name.match(/[A-Za-z0-9]/)?.[0] ?? '?').toUpperCase()

async function main() {
  // Map each brand key to its real asset filename (png or jpg).
  const files = await readdir(join(ROOT, 'assets', 'brands'))
  const fileFor = new Map()
  for (const f of files) {
    const key = f.replace(/\.(png|jpg)$/i, '')
    if (f !== key) fileFor.set(key, f)
  }

  // --- services.ts ---
  const rows = BRANDS.map(
    (b) =>
      `  { name: ${JSON.stringify(b.name)}, brandKey: '${b.key}', color: '${b.color}', ` +
      `initial: '${initialOf(b.name)}', category: ${JSON.stringify(b.category)}, domain: '${b.domain}' },`,
  ).join('\n')

  const servicesTs = `// AUTO-GENERATED by scripts/generate-brands.mjs — do not edit by hand.
export interface Service {
  name: string
  brandKey: string
  color: string
  initial: string
  category: string
  domain: string
}

export const POPULAR_SERVICES: Service[] = [
${rows}
]
`
  await writeFile(join(ROOT, 'src', 'constants', 'services.ts'), servicesTs)

  // --- brandLogos.ts (the static require map, its own file so brand.ts stays small) ---
  const logoLines = BRANDS.filter((b) => fileFor.has(b.key))
    .map((b) => `  '${b.key}': require('../../assets/brands/${fileFor.get(b.key)}'),`)
    .join('\n')

  const logosTs = `// AUTO-GENERATED by scripts/generate-brands.mjs — do not edit by hand.
// require() must be static, so this is an explicit brandKey -> asset map.
export const LOGOS: Record<string, number> = {
${logoLines}
}
`
  await writeFile(join(ROOT, 'src', 'utils', 'brandLogos.ts'), logosTs)

  // --- brand.ts (logic only) ---
  const brandTs = `import { POPULAR_SERVICES } from '@/constants/services'
import { LOGOS } from '@/utils/brandLogos'

export interface BrandVisual {
  color: string
  initial: string
  /** require()'d logo image source, or null to fall back to the colored initial. */
  logo: number | null
}

/**
 * Resolve a brand's display visuals from its brand_key / name / stored color.
 * Returns a logo image when one exists, else a colored badge + first letter.
 */
export function getBrandVisual(
  brandKey: string | null,
  name: string,
  color?: string | null,
): BrandVisual {
  const match = POPULAR_SERVICES.find((s) => s.brandKey === brandKey)
  return {
    color: color ?? match?.color ?? '#7C4DFF',
    initial: (match?.initial ?? name.charAt(0) ?? '?').toUpperCase(),
    logo: (brandKey ? LOGOS[brandKey] : undefined) ?? null,
  }
}
`
  await writeFile(join(ROOT, 'src', 'utils', 'brand.ts'), brandTs)

  console.log(`Generated services.ts (${BRANDS.length} services) and brand.ts (${logoLines.split('\n').length} logos).`)
}

main().catch((e) => { console.error(e); process.exit(1) })
